Some settings improvements
felixwiemuth/SimpleReminder pull request #11
Opened 2021-04-19 15:55 UTC by TacoTheDank

### 1st commit
- Use SwitchPreferenceCompat (from #8)

### 2nd commit
- Use FragmentContainerView for the settings fragment (go [here](https://developer.android.com/jetpack/androidx/releases/fragment), do Ctrl + F, and put "FragmentContainerView" in the box to see related info and changes, as well as the [reasons for its creation](https://developer.android.com/jetpack/androidx/releases/fragment#1.2.0-alpha02))

### 3rd commit
- Remove redundant getPreferenceScreen calls
- Don't reserve icon space for settings without icons (this makes the settings look nicer margin-wise)

2021-04-22 16:43 UTC, felixwiemuth commented
This looks good.

Thanks also for the third commit, I already noticed the space next to each preference and that actually many apps have it and was wondering where it comes from. Could you please change the commit title and message to something more descriptive? Basically what you already wrote in the description here is fine.

2021-04-22 16:44 UTC, felixwiemuth requested changes
Update commit message of last commit.

2021-04-26 15:25 UTC, felixwiemuth approved these changes

2021-04-26 15:42 UTC, felixwiemuth commented
Thanks! I added you to the contributors list (which in addition might be shown in the app), do you want anything changed for your entry? You can choose a different display name (the link will always be to the Github profile) and optionally have an email address added.

2021-04-27 15:36 UTC, TacoTheDank commented
@felixwiemuth Nope, you can just keep it as is if you wish :)

2021-04-27 19:44 UTC, felixwiemuth commented
Okay, thanks again for your effort! If you are interested in contributing more, let me know and we can have a chat. :)

2021-04-27 19:44 UTC, merged